### PR TITLE
implementing more general binning in kdcount.correlate

### PR DESCRIPTION
**Pull request by nickhand**
- `Binning` base class just takes the edges now
- linear/log spacing case determined from edges and same code used
- for general, non-uniform binning case, numpy.digitize is used
- also, cleaned up the code in paircount.**init** to use a context manager, which I think is a bit more clear for the initialization and finalize methods

### CODE REVIEW

**Comment by nickhand** [comment]
what do you think, @rainwoodman? 

the correlate tests here seem to work and I've confirmed no changes in the results of the nbodykit tests. looks like your new FOF changes broke those tests, though

**Comment by nickhand** [comment]
Okay, I agree the bins are (min, max], which should be the behavior of digitize(..., right=True). I've implemented the same behavior using searchsorted instead. It's essentially the same exact function, except with binary search.

**Comment by nickhand** [comment]
shall we merge this?

**Comment by rainwoodman** [comment]
Sure!

**Comment by rainwoodman** [comment]
I uploaded 0.3.2 to pypi.

**Pull request merged**
